trigger:
- main

pool:
- task: Docker@2
  inputs:
    containerRegistry: 'dotnetmssqlpf1966'
    repository: 'dotnetsql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest



